image: "chef/chefdk:1.0.3"

# TODO
# cache:

services:
  - docker:dind

before_script:
  - chef --version

test:
  script:
    - cookstyle
    - foodcritic --exclude test --epic-fail any .
    - kitchen test
