image: "kevinreedy/docker-chefdk:dokken-fix-20161121"

before_script:
  - apt-get update && apt-get -y install rsync
  - chef --version

test:
  script:
    - cookstyle
    - foodcritic --exclude test --epic-fail any .
    - kitchen test
