image: "kevinreedy/docker-chefdk:1.1.13"

before_script:
  - env
  - chef --version

stages:
  - lint
  - unit
  - integration

lint:
  stage: lint
  script:
    - cookstyle
    - foodcritic --exclude test --epic-fail any .

unit:
  stage: unit
  script:
    - rspec

.integration: &tk
  stage: integration
  before_script:
    - env
    - chef --version
    - apt-get update && apt-get -y install rsync
  # TODO: script might run verify against an existing container if it matches; after_script might also be destroying other projects' containers if they are running in parallel
  script:
    - kitchen verify $CI_BUILD_NAME
  after_script:
    - kitchen destroy $CI_BUILD_NAME

"centos-5":
  <<: *tk

"centos-6":
  <<: *tk

"centos-7":
  <<: *tk

"debian-7":
  <<: *tk

"debian-8":
  <<: *tk

"ubuntu-1204":
  <<: *tk

"ubuntu-1404":
  <<: *tk

"ubuntu-1604":
  <<: *tk

