image: "kevinreedy/chefdk-debug:0.0.5"

# TODO
# cache:

services:
  - docker:dind

before_script:
  - apt-get update && apt-get -y install rsync
  - chef --version

test:
  script:
    - cookstyle
    - foodcritic --exclude test --epic-fail any .
    - kitchen test
