image: "kevinreedy/docker-chefdk:dokken-fix-20161121"

before_script:
  - env
  - chef --version

stages:
  - lint
  - unit
  - integration

lint:
  stage: lint
  script:
    - cookstyle
    - foodcritic --exclude test --epic-fail any .

unit:
  stage: unit
  script:
    - echo rspec

.integration: &tk
  stage: integration
  before_script:
    - env
    - chef --version
    - apt-get update && apt-get -y install rsync
  script:
    - kitchen verify $CI_BUILD_NAME
  after_script:
    - kitchen destroy $CI_BUILD_NAME

"ubuntu-1604":
  <<: *tk

"centos-7":
  <<: *tk
