---
driver:
  name: dokken
  chef_version: latest

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec

platforms:
- name: centos_5
  driver:
    image: centos:5

- name: centos_6
  driver:
    image: centos:6

- name: centos_7
  driver:
    image: centos:7

- name: debian_7
  driver:
    image: debian:7

- name: debian_8
  driver:
    image: debian:8

- name: ubuntu_12.04
  driver:
    image: ubuntu:12.04

- name: ubuntu_14.04
  driver:
    image: ubuntu:14.04

- name: ubuntu_16.04
  driver:
    image: ubuntu:16.04


suites:
  - name: default
    run_list:
      - recipe[test_cookbook::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
