---
driver:
  name: dokken
  chef_version: latest

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec

platforms:
- name: centos-5
  driver:
    image: centos:5

- name: centos-6
  driver:
    image: centos:6

- name: centos-7
  driver:
    image: centos:7

- name: debian-7
  driver:
    image: debian:7

- name: debian-8
  driver:
    image: debian:8

- name: ubuntu-12.04
  driver:
    image: ubuntu:12.04

- name: ubuntu-14.04
  driver:
    image: ubuntu:14.04

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04


suites:
  - name: default
    run_list:
      - recipe[test_cookbook::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
