---
driver:
  name: dokken
  chef_version: latest

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec

platforms:
- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
- name: centos-7
  driver:
    image: centos:7

suites:
  - name: default
    run_list:
      - recipe[test_cookbook::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
